// File generated by FlutterFire CLI.
// Contains Firebase configuration for your application

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: To use this file, you need to replace the placeholder values below
/// with your actual Firebase configuration values from:
/// 1. Go to your Firebase project console: https://console.firebase.google.com/
/// 2. Navigate to Project Settings (gear icon)
/// 3. Scroll down to "Your apps" section
/// 4. Add a web app if you don't have one already
/// 5. Copy the configuration values from the Firebase SDK snippet
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // REPLACE THESE VALUES with your actual Firebase configuration
  // From Firebase Console > Project settings > Your apps > SDK setup and configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:web:b7e3a2cf9f5bdb82d9aad2',
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    authDomain: 'loco-game-ul9tw4.firebaseapp.com',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
    measurementId: 'G-measurement-id', // Replace with actual measurement ID if needed
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:android:appid', // Replace with actual Android app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:ios:appid', // Replace with actual iOS app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
    iosClientId: 'ios-client-id', // Replace with actual iOS client ID
    iosBundleId: 'com.locofo.dashboard', // Replace with actual iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:macos:appid', // Replace with actual macOS app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
    iosClientId: 'macos-client-id', // Replace with actual macOS client ID
    iosBundleId: 'com.locofo.dashboard', // Replace with actual macOS bundle ID
  );
} 