// File generated by FlutterFire CLI.
// Contains Firebase configuration for your application

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: To use this file, you need to replace the placeholder values below
/// with your actual Firebase configuration values from:
/// 1. Go to your Firebase project console: https://console.firebase.google.com/
/// 2. Navigate to Project Settings (gear icon)
/// 3. Scroll down to "Your apps" section
/// 4. Add a web app if you don't have one already
/// 5. Copy the configuration values from the Firebase SDK snippet
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // REPLACE THESE VALUES with your actual Firebase configuration
  // From Firebase Console > Project settings > Your apps > SDK setup and configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgpaJ1UMaKd1TxMhunRsOlieN8mWpjM4',
    authDomain: 'locotag.firebaseapp.com',
    projectId: 'locotag',
    storageBucket: 'locotag.firebasestorage.app',
    messagingSenderId: '783647689390',
    appId: '1:783647689390:web:1b45930c96bc4beb863b3f',
    measurementId: 'G-MRF3817G7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:android:appid', // Replace with actual Android app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:ios:appid', // Replace with actual iOS app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
    iosClientId: 'ios-client-id', // Replace with actual iOS client ID
    iosBundleId: 'com.locofo.dashboard', // Replace with actual iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-9fLyQld-UGv4tFmptS372y_zs6N03I',
    appId: '1:352659986366:macos:appid', // Replace with actual macOS app ID
    messagingSenderId: '352659986366',
    projectId: 'loco-game-ul9tw4',
    storageBucket: 'loco-game-ul9tw4.appspot.com',
    iosClientId: 'macos-client-id', // Replace with actual macOS client ID
    iosBundleId: 'com.locofo.dashboard', // Replace with actual macOS bundle ID
  );
} 